### ISSUE TITLE
[ENH] Gene browser/phenotype tool: SVG numbers are too small on smaller screen sizes

### ISSUE THREAD

**Issue by joankosev** [iossifovlab/gpfjs#1031]

**Comment by IvoStefanov** [comment]
Gene plot can be resized too much. Introduce sensible minimum so small screen sizes use scrolls and see the plot (around 1250px width?).
![image](https://github.com/user-attachments/assets/5d84ff9e-a16e-4d8c-b1c8-df5364e55bf0)

Pheno tool results are the same case. Introduce minimum width size (around 1000px width?).
![image](https://github.com/user-attachments/assets/9b2a336a-c7d7-41f3-90d8-4f9bbb2c7b40)
