### ISSUE TITLE
[ENH] Stream downloads

### ISSUE THREAD

**Issue by iordanivanov** [iossifovlab/gpfjs#617]
**Is your feature request related to a problem? Please describe.**
When I click a download button, I have to wait until the whole download is complete for the file to be saved. The feedback in this scenario is lacking.

**Describe the solution you'd like**
I would like to see the download/saving of the file begin immediately upon clicking the button, and see it happen in action.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by livovachkov** [comment]
Perhaps closed?
