### ISSUE TITLE
[BUG] No unit tests for GenotypeBrowserComponent

### ISSUE THREAD

**Issue by iordanivanov** [iossifovlab/gpfjs#619]
**What happened**:
I didn't see unit tests for GenotypeBrowserComponent.
**What you expected to happen**:
See unit tests for GenotypeBrowserComponent.
**Anything else we need to know?**:
Writing the test bed for GenotypeBrowserComponent is tedious. :)

**Comment by livovachkov** [comment]
I have added create and download tests but forgot to close the issue.
