### ISSUE TITLE
[BUG] Problem rendering transcripts in gene browser

### ISSUE THREAD

**Issue by livovachkov** [iossifovlab/gpfjs#637]
**What happened**: When a gene with a large number of exons is selected in the gene browser, there is a problem rendering transcripts since the distance between the exons could become less than a pixel. 

One such gene is TTN, which consists of 364 exons. 

The second screenshot shows the current distance between exons in pixels.

**Gene**: TTN
**Genome**: HG38 on production data
**Study**: SPARK Consortium WES batch 1
**Exons length**: 364
**Distance between them in pixels**: Provided in the second screenshot

![Screenshot_20221125_140017](https://user-images.githubusercontent.com/71081781/203981638-b252f284-2f0f-4052-954a-796c99a37a4a.png)
![Screenshot_20221125_141259](https://user-images.githubusercontent.com/71081781/203983667-cde55ed4-017c-4c9d-8d77-5d0408d39d05.png)

**Comment by lchorbadjiev** [comment]
<img width="1999" alt="Screenshot 2022-11-25 at 14 28 39" src="https://user-images.githubusercontent.com/827119/203986224-034e4bfa-42f9-41ec-b000-db56918c9b7f.png">

**Comment by livovachkov** [comment]
This issue is not useful to be changed.
