### ISSUE TITLE
[gpfjs] issues with visually flickering components

### ISSUE THREAD

**Issue by joankosev** [iossifovlab/gpfjs#723]
make a list of components that flicker when loading

1) [done] agp search
2) [done] enrichment models
3) [move to #776] gene sets
4) [move to #776] gene scores
5) [done] the url in save/share query
6) [done] dataset statistics, families by pedigree
- [done] modal, but only on slow internet?
- [done] (but the solution isn't much better, ask to see local stash) pedigrees after filtering with tags (the ngFor can be felt)
7) [moved to #738] the newly added downloading text change - see if you can make a browser tooltip at bottom-left
8) [another task?] the entire tool / dataset page (see the screencast)
9) [won't fix] the "~" in histogram component

**Comment by joankosev** [comment]
Also the "Table Preview" button gets disabled when the "no gene scores available" text shows

**Comment by iordanivanov** [comment]
https://user-images.githubusercontent.com/15002638/216046077-d403afbb-7948-47cc-b620-3bea2961c6ab.mp4

**Comment by joankosev** [comment]
The solution for the gene scores and gene sets isn't good. Write a better one
