### ISSUE TITLE
[BUG] Open link in new tab firefox issue

### ISSUE THREAD

**Issue by joankosev** [iossifovlab/gpfjs#725]
should open link in new tab without navigating to it;
also make dropdown not close on middleclick
https://developer.mozilla.org/en-US/docs/Web/API/Window/open#usability_issues
need further research, MDN recommends against using window.open. We currently use it on 4-5 places

**Comment by livovachkov** [comment]
"Tab behaviour is controlled by the browser.

You wont have any way of controlling it from javascript.

Being able to control that kind of behaviour would be a serious security concern" as copied by StackOverflow

https://stackoverflow.com/questions/6213807/open-a-new-tab-with-javascript-but-stay-on-current-tab

https://stackoverflow.com/questions/49551012/a-target-blank-onlick-should-open-a-new-tab-but-the-focus-should-be-on-curr?noredirect=1&lq=1
