### ISSUE TITLE
[ENH] make file downloads smoother

### ISSUE THREAD

**Issue by joankosev** [iossifovlab/gpfjs#738]
currently when clicking on a download button, for example in the genotype browser, the button text would switch from "Download" to "Downloading" to indicate a download has started. After 5-10 seconds, the file would be ready and the browser will then start the download.
Ideally, on download click, the browser will immediately start to download a file, even if it takes 5-10 seconds

**Comment by livovachkov** [comment]
This issue has been fixed.
