### ISSUE TITLE
[ENH] Phenotype browser Measure Description content is unreadable

### ISSUE THREAD

**Issue by IvoStefanov** [iossifovlab/gpfjs#784]
**Is your feature request related to a problem? Please describe.**
Measure Description content is unreadable (hover text flickers when cell is scrolled, content is much bigger than cell, horizontal scroll appears sometimes and makes things worse)
![image](https://user-images.githubusercontent.com/71064753/228495473-f2c6bc41-c746-458b-a1c6-de71e7476fbc.png)

**Describe the solution you'd like**
Add better hover text that does not move when text is scrolled.
Remove horizontal text scrolling - fit text horizontally.
Truncate text vertically somehow?

**Comment by joankosev** [comment]
DONE
