### ISSUE TITLE
[ENH] Filters components refactor

### ISSUE THREAD

**Issue by iordanivanov** [iossifovlab/gpfjs#811]
Filters - continuous, multi-continuous, categorical, filter blocks (person/family) are in need of a refactor as there is a lot of logic that is prone to bugs. One example is the state restoring logic - as of writing this issue, the block component and the multi-continuous filter both attempt to restore state which can lead to issues. Also, currently we work under the assumption that only one multi-continuous filter can exist at a time - if there are more, the state restoring logic could break.

**Comment by joankosev** [comment]
related https://github.com/iossifovlab/gpfjs/issues/729

**Comment by IvoStefanov** [comment]
Addressed/refactored in NGRX state transition.
But https://github.com/iossifovlab/gpfjs/issues/729 is still a valid issue, the overall code of 3-5 components can be simplified with the implementation of different states for family and person filters.
