### ISSUE TITLE
[ENH] Gene browser - maintain input focus when a query is made for a non-existent gene

### ISSUE THREAD

**Issue by iordanivanov** [iossifovlab/gpfjs#816]
When you hit Return/Enter on a gene symbol that doesn't exist (such as "PGOZ"), we should maintain the focus on the input field so that it's easier to correct your mistake.

Also perhaps update error message style:
![image](https://github.com/iossifovlab/gpfjs/assets/71064753/9c134374-af0c-4a55-beca-5d52f1046f6f)

**Comment by livovachkov** [comment]
This is covered in #762

**Comment by joankosev** [comment]
also when the user selects the field to correct their mistake, it clears the input which can be annoying
