### ISSUE TITLE
[ENH] Update Gene Browser gene select UI

### ISSUE THREAD

**Issue by IvoStefanov** [iossifovlab/gpfjs#829]
**Is your feature request related to a problem? Please describe.**
Old UI is a bit chaotic and wasting vertical space.
![image](https://github.com/iossifovlab/gpfjs/assets/71064753/b3eaa1da-b75f-469f-a8e3-e7d7620f0ad9)

**Describe the solution you'd like**
Update it to be more in line with newer UIs?
![image](https://github.com/iossifovlab/gpfjs/assets/71064753/e23f4fb9-3877-4ce6-a80e-cc4a3c59dfa4)
Bigger wireframe:
![image](https://github.com/iossifovlab/gpfjs/assets/71064753/68c19820-2fbf-4726-a6ea-66331c5b234a)

(also make error message appear to the right of Go button not below)

**Comment by joankosev** [comment]
Coding only checkbox can get hidden by the dropdown, perhaps it should be moved on the right as well?
