### ISSUE TITLE
[BUG] Gene browser gene symbol input field clears on cursor re-entering the window

### ISSUE THREAD

**Issue by iordanivanov** [iossifovlab/gpfjs#908]
To reproduce:
1. Type in anything in the gene symbol input field
2. Move cursor outside of browser window
3. Move it back in, refocusing the window 
4. This will clear the gene symbol input field

**Comment by joankosev** [comment]
Can't reproduce on windows 10 firefox and chrome

**Comment by IvoStefanov** [comment]
Can't reproduce.
