### ISSUE TITLE
[BUG] Genomic scores dropdown is too wide

### ISSUE THREAD

**Issue by IlinaGergova** [iossifovlab/gpfjs#955]
**What happened**:
Genomic scores dropdown is wider and gets out of the browser when the window is smaller
![image](https://github.com/iossifovlab/gpfjs/assets/56651698/dd8ea02c-1e2a-4a17-bb01-c9d99cae794c)

**What you expected to happen**:
Need to have responsive design.

**Comment by joankosev** [comment]
related https://github.com/iossifovlab/gpfjs/issues/980

**Comment by joankosev** [comment]
html <select> element limitation. If we want this fixed, another dropdown should be used
